baseURL = 'https://www.emoses.org/'
languageCode = 'en-us'
theme = 'hugo-kiera'
title = 'Evan Moses'

[markup.highlight]
        noClasses = false

[author]
    name = "Evan Moses"           #Author name
    github = "emoses"         #Github username
    linkedin = "emoses"       #LinkedIn username
    email = "webmaster@emoses.org"
    mastodon = "hachyderm.io/@emoses"

[params]
    tagline = "My blog and projects"
    #customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode
    customCSS = ['css/more-styles.css', 'css/style-overrides.css', 'css/syntax.css']

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/emoses"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/emoses"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://hachyderm.io/@emoses"