baseURL = 'https://www.emoses.org/'
languageCode = 'en-us'
theme = 'hugo-kiera'
title = 'Evan Moses'

[markup.highlight]
    noClasses = false
    style = 'monokai'


[author]
    name = "Evan Moses"           #Author name
    github = "emoses"         #Github username
    linkedin = "emoses"       #LinkedIn username
    email = "webmaster@emoses.org"
    mastodon = "hachyderm.io/@emoses"
    bluesky = "emoses.org"

[params]
    tagline = "My blog and projects"
    description = "Personal blog and projects.  Emacs, programming, making, nerdiness."
    disableDarkModeCSS = false # disables css style for users using dark-mode
    customCSS = ['css/more-styles.css', 'css/style-overrides.css', 'css/syntax.css']
    site_logo = "/img/profile.png"
    site_logo_classes = "logo"
    mainSections = ['posts', 'games']

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/emoses"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/emoses"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://hachyderm.io/@emoses"

[[params.socialIcons]]
icon = "fab fa-bluesky"
title = "BlueSky"
url = "https://bsky.app/@emoses.org"
